=== Igorek2312/LibreLingvo/src/test/resources/test.dtd
<!ELEMENT dataset (
    ClientDetails*,
    Lesson*,
    Role*,
    Tag*,
    Translation*,
    TranslationTag*,
    User*,
    UserRole*,
    Word*,
    hibernate_sequence*,
    oauth_access_token*,
    oauth_client_details*,
    oauth_client_token*,
    oauth_code*,
    oauth_refresh_token*,
    schema_version*)>

<!ELEMENT ClientDetails EMPTY>
<!ATTLIST ClientDetails
    appId CDATA #REQUIRED
    resourceIds CDATA #IMPLIED
    appSecret CDATA #IMPLIED
    scope CDATA #IMPLIED
    grantTypes CDATA #IMPLIED
    redirectUrl CDATA #IMPLIED
    authorities CDATA #IMPLIED
    access_token_validity CDATA #IMPLIED
    refresh_token_validity CDATA #IMPLIED
    additionalInformation CDATA #IMPLIED
    autoApproveScopes CDATA #IMPLIED
>

<!ELEMENT Lesson EMPTY>
<!ATTLIST Lesson
    id CDATA #REQUIRED
    completedPartsOfLesson CDATA #REQUIRED
    maxPartsOfLesson CDATA #REQUIRED
    waitUnitNextLessonPart CDATA #IMPLIED
>

<!ELEMENT Role EMPTY>
<!ATTLIST Role
    id CDATA #REQUIRED
    name CDATA #REQUIRED
>

<!ELEMENT Tag EMPTY>
<!ATTLIST Tag
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    position CDATA #IMPLIED
    user_id CDATA #IMPLIED
>

<!ELEMENT Translation EMPTY>
<!ATTLIST Translation
    id CDATA #REQUIRED
    lastModificationDate CDATA #REQUIRED
    learned CDATA #REQUIRED
    learnedDate CDATA #IMPLIED
    note CDATA #IMPLIED
    partOfSpeech CDATA #REQUIRED
    views CDATA #REQUIRED
    lesson_id CDATA #IMPLIED
    resultWord_id CDATA #IMPLIED
    sourceWord_id CDATA #IMPLIED
    user_id CDATA #IMPLIED
>

<!ELEMENT TranslationTag EMPTY>
<!ATTLIST TranslationTag
    tagId CDATA #REQUIRED
    translationId CDATA #REQUIRED
>

<!ELEMENT User EMPTY>
<!ATTLIST User
    id CDATA #REQUIRED
    activationKey CDATA #IMPLIED
    autoPlayDuringLesson CDATA #REQUIRED
    email CDATA #REQUIRED
    enabled CDATA #REQUIRED
    lessonPartsCount CDATA #REQUIRED
    minutesBetweenLessonParts CDATA #REQUIRED
    name CDATA #IMPLIED
    nonLocked CDATA #REQUIRED
    password CDATA #IMPLIED
    registrationDate CDATA #IMPLIED
    resetKey CDATA #IMPLIED
    translationsInOneLesson CDATA #REQUIRED
>

<!ELEMENT UserRole EMPTY>
<!ATTLIST UserRole
    userId CDATA #REQUIRED
    roleId CDATA #REQUIRED
>

<!ELEMENT Word EMPTY>
<!ATTLIST Word
    id CDATA #REQUIRED
    langCode CDATA #IMPLIED
    text CDATA #IMPLIED
>

<!ELEMENT hibernate_sequence EMPTY>
<!ATTLIST hibernate_sequence
    next_val CDATA #IMPLIED
>

<!ELEMENT oauth_access_token EMPTY>
<!ATTLIST oauth_access_token
    token_id CDATA #IMPLIED
    token CDATA #IMPLIED
    authentication_id CDATA #REQUIRED
    user_name CDATA #IMPLIED
    client_id CDATA #IMPLIED
    authentication CDATA #IMPLIED
    refresh_token CDATA #IMPLIED
>

<!ELEMENT oauth_client_details EMPTY>
<!ATTLIST oauth_client_details
    client_id CDATA #REQUIRED
    resource_ids CDATA #IMPLIED
    client_secret CDATA #IMPLIED
    scope CDATA #IMPLIED
    authorized_grant_types CDATA #IMPLIED
    web_server_redirect_uri CDATA #IMPLIED
    authorities CDATA #IMPLIED
    access_token_validity CDATA #IMPLIED
    refresh_token_validity CDATA #IMPLIED
    additional_information CDATA #IMPLIED
    autoapprove CDATA #IMPLIED
>

<!ELEMENT oauth_client_token EMPTY>
<!ATTLIST oauth_client_token
    token_id CDATA #IMPLIED
    token CDATA #IMPLIED
    authentication_id CDATA #REQUIRED
    user_name CDATA #IMPLIED
    client_id CDATA #IMPLIED
>

<!ELEMENT oauth_code EMPTY>
<!ATTLIST oauth_code
    code CDATA #IMPLIED
    authentication CDATA #IMPLIED
>

<!ELEMENT oauth_refresh_token EMPTY>
<!ATTLIST oauth_refresh_token
    token_id CDATA #IMPLIED
    token CDATA #IMPLIED
    authentication CDATA #IMPLIED
>

<!ELEMENT schema_version EMPTY>
<!ATTLIST schema_version
    installed_rank CDATA #REQUIRED
    version CDATA #IMPLIED
    description CDATA #REQUIRED
    type CDATA #REQUIRED
    script CDATA #REQUIRED
    checksum CDATA #IMPLIED
    installed_by CDATA #REQUIRED
    installed_on CDATA #REQUIRED
    execution_time CDATA #REQUIRED
    success CDATA #REQUIRED
>

=== Igorek2312/LibreLingvo/src/test/resources/dao/user/translations-test-case.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../../test.dtd">
<dataset>
    <Role id="1" name="ROLE_USER"/>

    <User id="1" email="testemail@example.com" password="1234" name="test" nonLocked="true"
          autoPlayDuringLesson="true" enabled="true" lessonPartsCount="3" minutesBetweenLessonParts="10"
          translationsInOneLesson="10" registrationDate="2016-12-04 10:21:53" activationKey="foo-activation-key"
          resetKey="foo-reset-key"/>

    <UserRole userId="1" roleId="1"/>

    <Word id="1" text="sample" langCode="en"/>
    <Word id="3" text="code" langCode="en"/>
    <Word id="5" text="butterfly" langCode="en"/>
    <Word id="7" text="log in" langCode="en"/>
    <Word id="2" text="зразок" langCode="uk"/>
    <Word id="4" text="код" langCode="uk"/>
    <Word id="6" text="метелик" langCode="uk"/>
    <Word id="8" text="увійти" langCode="uk"/>
    <Word id="10" text="пример" langCode="ru"/>

    <Translation id="1" sourceWord_id="1" resultWord_id="2" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOUN" views="1" user_id="1"/>
    <Translation id="2" sourceWord_id="3" resultWord_id="4" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOUN" views="1" user_id="1"/>
    <Translation id="3" sourceWord_id="5" resultWord_id="6" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1"/>
    <Translation id="4" sourceWord_id="7" resultWord_id="8" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1"/>
    <Translation id="5" sourceWord_id="1" resultWord_id="10" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1"/>
</dataset>

=== Igorek2312/LibreLingvo/src/test/resources/dao/user/after-removing-translation-tag.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../../test.dtd">
<dataset>
    <Role id="1" name="ROLE_USER"/>

    <User id="1" email="testemail@example.com" password="1234" name="test" nonLocked="true"
          autoPlayDuringLesson="true" enabled="true" lessonPartsCount="3" minutesBetweenLessonParts="10"
          translationsInOneLesson="10" registrationDate="2016-12-04 10:21:53" activationKey="foo-activation-key"
          resetKey="foo-reset-key"/>

    <UserRole userId="1" roleId="1"/>

    <Word id="1" text="sample" langCode="en"/>
    <Word id="3" text="code" langCode="en"/>
    <Word id="5" text="butterfly" langCode="en"/>
    <Word id="7" text="log in" langCode="en"/>
    <Word id="9" text="teapot" langCode="en"/>
    <Word id="11" text="sign up" langCode="en"/>
    <Word id="2" text="зразок" langCode="uk"/>
    <Word id="4" text="код" langCode="uk"/>
    <Word id="6" text="метелик" langCode="uk"/>
    <Word id="8" text="увійти" langCode="uk"/>
    <Word id="10" text="чайник" langCode="uk"/>
    <Word id="12" text="зареєструватися" langCode="uk"/>
    <Word id="100" text="пример" langCode="ru"/>

    <Tag id="1" name="phrasal verbs" position="0" user_id="1"/>
    <Tag id="2" name="empty tag" position="1" user_id="1"/>

    <Lesson id="1"  completedPartsOfLesson="1" maxPartsOfLesson="3"/>

    <Translation id="1" sourceWord_id="1" resultWord_id="2" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOUN" views="1" user_id="1"/>
    <Translation id="2" sourceWord_id="3" resultWord_id="4" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOUN" views="1" user_id="1"/>
    <Translation id="3" sourceWord_id="5" resultWord_id="6" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1"/>
    <Translation id="4" sourceWord_id="7" resultWord_id="8" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1"/>
    <Translation id="5" sourceWord_id="1" resultWord_id="100" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1"/>
    <Translation id="6" sourceWord_id="9" resultWord_id="10" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1" lesson_id="1"/>
    <Translation id="7" sourceWord_id="11" resultWord_id="12" learnedDate="2016-12-04 10:21:53" lastModificationDate="2016-12-04 10:21:53" learned="false" partOfSpeech="NOT_DEFINED" views="1" user_id="1" lesson_id="1"/>

    <TranslationTag tagId="1" translationId="7"/>
</dataset>
